global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#achurikov_churikov'
