version: '3.3'
services:

  post_db:
    image: mongo:${ver_mong}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
          #    build: ./ui
    image: ${USERNAME}/ui:${ver_ui}
    ports:
      - ${host_port}:${cont_port}/tcp
    networks:
      - front_net
 
  post:
          #    build: ./post-py
    image: ${USERNAME}/post:${ver_post}
    networks:
      - back_net
      - front_net

  comment:
          #    build: ./comment
    image: ${USERNAME}/comment:${ver_comm}
    networks:
      - back_net
      - front_net
  
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net
  
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
