version: '3.3'
services:

  post_db:
    image: mongo:${ver_mong}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
          #    build: ./ui
    image: ${USERNAME}/ui:${ver_ui}
    ports:
      - ${host_port}:${cont_port}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
          #    build: ./post-py
    image: ${USERNAME}/post:${ver_post}
    networks:
      - back_net
      - front_net
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED} 

  comment:
          #    build: ./comment
    image: ${USERNAME}/comment:${ver_comm}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:  
  post_db:

networks:
  back_net:
  front_net:
