version: '3.3'
services:

  post_db:
    image: mongo:${ver_mong}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
          #    build: ./ui
    image: ${USERNAME}/ui:${ver_ui}
    ports:
      - ${host_port}:${cont_port}/tcp
    networks:
      - front_net
 
  post:
          #    build: ./post-py
    image: ${USERNAME}/post:${ver_post}
    networks:
      - back_net
      - front_net

  comment:
          #    build: ./comment
    image: ${USERNAME}/comment:${ver_comm}
    networks:
      - back_net
      - front_net

volumes:  
  post_db:

networks:
  back_net:
  front_net:
